import { CVVariant, MasterProfile } from "./profile-types";

const LATEX_ESCAPE_MAP: Record<string, string> = {
  "\\": "\\textbackslash{}",
  "&": "\\&",
  "%": "\\%",
  $: "\\$",
  "#": "\\#",
  _: "\\_",
  "{": "\\{",
  "}": "\\}",
  "~": "\\textasciitilde{}",
  "^": "\\textasciicircum{}",
};

export function escapeLatex(input: string): string {
  return input
    .split("")
    .map((c) => LATEX_ESCAPE_MAP[c] ?? c)
    .join("");
}

function nonEmpty(s: string | undefined | null): string {
  return (s ?? "").trim();
}

export function renderLatex(
  variant: CVVariant,
  profile: MasterProfile
): string {
  const blockById = new Map(profile.experience_blocks.map((b) => [b.id, b]));

  const contactPieces: string[] = [];
  if (nonEmpty(profile.contact.location))
    contactPieces.push(escapeLatex(profile.contact.location!));
  if (nonEmpty(profile.contact.phone))
    contactPieces.push(escapeLatex(profile.contact.phone!));
  if (nonEmpty(profile.contact.email))
    contactPieces.push(escapeLatex(profile.contact.email!));
  if (nonEmpty(profile.contact.linkedin))
    contactPieces.push(
      `\\href{https://${profile.contact.linkedin}}{${escapeLatex(profile.contact.linkedin!)}}`
    );
  if (nonEmpty(profile.contact.github))
    contactPieces.push(
      `\\href{https://${profile.contact.github}}{${escapeLatex(profile.contact.github!)}}`
    );

  const contactLine = contactPieces.join(
    " \\quad\\textbullet\\quad\n  "
  );

  const experienceSections = variant.experience_order
    .map((id) => {
      const block = blockById.get(id);
      const variantBlock = variant.experience.find((e) => e.block_id === id);
      if (!block || !variantBlock) return "";

      const bullets = variantBlock.bullets
        .map((b) => `  \\item ${escapeLatex(b)}`)
        .join("\n");

      const contextLine = nonEmpty(block.context)
        ? `\n${escapeLatex(block.context)}\n`
        : "";

      return `\\jobtitle{${escapeLatex(block.role)}}{${escapeLatex(
        block.company
      )}}{${escapeLatex(block.period)}}
${contextLine}
\\begin{itemize}
${bullets}
\\end{itemize}`;
    })
    .filter((s) => s.length > 0)
    .join("\n\n");

  const educationRows = profile.education
    .map(
      (e) => `  \\textbf{\\color{darktext}${escapeLatex(e.degree)}}
    & \\textcolor{lightgray}{\\small ${escapeLatex(e.period)}} \\\\
  \\textit{\\color{graytext}${escapeLatex(e.institution)}} & \\\\`
    )
    .join("\n");

  const focusLines = profile.education
    .filter((e) => nonEmpty(e.focus))
    .map((e) => `{\\small\\color{graytext}${escapeLatex(e.focus!)}}`)
    .join("\\\\\n");

  const certs = profile.certifications
    .map((c) => escapeLatex(c.name))
    .join(" \\quad\\textbullet\\quad ");

  const skillsRows = variant.skills
    .map(
      (g) =>
        `  ${escapeLatex(g.category)}: & ${g.items
          .map((i) => escapeLatex(i))
          .join(", ")} \\\\[4pt]`
    )
    .join("\n");

  const languages = profile.languages.length
    ? `  Languages: & ${profile.languages.map((l) => escapeLatex(l)).join(", ")} \\\\`
    : "";

  return `%% Generated by CV Factory — variant tailored from master_profile.json
\\documentclass[10pt, a4paper]{article}

\\usepackage[T1]{fontenc}
\\usepackage[utf8]{inputenc}
\\usepackage[a4paper, top=1.8cm, bottom=1.8cm, left=1.8cm, right=1.8cm]{geometry}
\\usepackage{xcolor}
\\usepackage{titlesec}
\\usepackage{enumitem}
\\usepackage{hyperref}
\\usepackage{array}
\\usepackage{tabularx}
\\usepackage{parskip}

\\definecolor{headblue}{HTML}{1F4E79}
\\definecolor{darktext}{HTML}{1A1A1A}
\\definecolor{graytext}{HTML}{555555}
\\definecolor{lightgray}{HTML}{888888}

\\hypersetup{colorlinks=true, urlcolor=headblue, linkcolor=headblue}

\\titleformat{\\section}
  {\\color{headblue}\\bfseries\\normalsize\\uppercase}
  {}{0em}{}
  [\\color{headblue}\\titlerule]
\\titlespacing{\\section}{0pt}{10pt}{5pt}

\\pagestyle{empty}

\\setlist[itemize]{
  leftmargin=1.4em,
  itemsep=2pt,
  parsep=0pt,
  topsep=3pt,
  label={\\textcolor{headblue}{\\textbullet}}
}

\\newcommand{\\jobtitle}[3]{%
  \\vspace{6pt}%
  \\noindent
  \\begin{tabularx}{\\linewidth}{@{}X r@{}}
    \\textbf{\\color{darktext}#1} \\textcolor{lightgray}{|} \\textit{\\color{graytext}#2}
    & \\textcolor{lightgray}{\\small #3}
  \\end{tabularx}%
  \\vspace{1pt}%
}

\\begin{document}

{\\color{headblue}\\Huge\\bfseries ${escapeLatex(profile.name)}}

\\vspace{4pt}
{\\small\\color{graytext}
  ${contactLine}
}

\\vspace{8pt}

\\section{Profile}

\\vspace{3pt}
${escapeLatex(variant.profile_summary)}

\\section{Experience}

${experienceSections}

\\section{Education}

\\vspace{3pt}
\\begin{tabularx}{\\linewidth}{@{}X r@{}}
${educationRows}
\\end{tabularx}

${focusLines ? `\\vspace{2pt}\n${focusLines}\n` : ""}
\\section{Certifications}

\\vspace{3pt}
{\\small
${certs}
}

\\section{Skills \\& Tools}

\\vspace{3pt}
\\begin{tabularx}{\\linewidth}{@{} >{\\bfseries\\color{darktext}}l X @{}}
${skillsRows}
${languages}
\\end{tabularx}

\\end{document}
`;
}
